[package]
name = "indexer-allocation"
version = "0.1.0"
edition = "2021"

[dependencies]
indexer-query = { path = "../query" }
serde = { workspace = true, features = ["derive"] }
thegraph-core.workspace = true
anyhow.workspace = true
