[common.indexer]
indexer_address = "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
operator_mnemonic = "foo bar baz ruux zorp quux quuz corge grault garply waldo fred"

[common.graph_node]
status_url = "http://localhost:8030/graphql"
query_base_url = "http://localhost:8000"

[common.database]
postgres_url = "postgresql://indexer@localhost:5432/indexer"

[common.network_subgraph]
query_url = "http://localhost:8000/subgraphs/id/QmXSS5oeWPxHGtsVNWsXSz3p67zoaaao9FtkxcCMg3A8RL"
syncing_interval = 60
# optional, default = false:
serve_subgraph = true
serve_auth_token = "i-need-network-subgraph-data"

[common.escrow_subgraph]
query_url = "http://localhost:8000/subgraphs/id/QmW2mc83Wi6PnxA5X4rzdnBY3sTZH8FVVJiwMYL9Y6Z4UY"
syncing_interval = 60
# optional, default = false:
serve_subgraph = false

[common.graph_network]
id = 1
chain_id = 1

[common.server]
url_prefix = "/"
host_and_port = "0.0.0.0:7600"
metrics_host_and_port = "0.0.0.0:7601"
# optional:
free_query_auth_token = "i-am-authorized-right?"

[common.tap]
chain_id = 1
receipts_verifier_address = "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
